# Generated by Django 5.2.1 on 2026-04-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chauffeur_details',
            field=models.TextField(blank=True, help_text='Pickup location, flight num, etc.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_chauffeur',
            field=models.BooleanField(default=False),
        ),
    ]
