# Generated by Django 6.0.3 on 2026-04-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('active', 'Active Rental'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Payment Failed'), ('rejected', 'Rejected by Admin')], db_index=True, default='pending', max_length=20),
        ),
    ]
