# Generated by Django 5.2.1 on 2026-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('weekend_surge', 'Weekend Surge'), ('peak_season', 'Peak Season'), ('low_season', 'Low Season'), ('holiday', 'Holiday'), ('last_minute', 'Last Minute Discount'), ('advance_booking', 'Advance Booking Discount'), ('long_rental', 'Long Rental Discount')], max_length=30)),
                ('applies_to_weekdays', models.CharField(blank=True, max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('min_days', models.PositiveIntegerField(blank=True, null=True)),
                ('days_before_start', models.PositiveIntegerField(blank=True, null=True)),
                ('modifier_type', models.CharField(choices=[('multiply', 'Multiply'), ('add_percent', 'Add Percent')], max_length=20)),
                ('modifier_value', models.DecimalField(decimal_places=4, max_digits=7)),
                ('applies_to_all', models.BooleanField(default=True)),
                ('applies_to_categories', models.CharField(blank=True, max_length=255)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
