# Generated by Django 6.0.3 on 2026-04-04 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='sedan', max_length=50)),
                ('model_group', models.SlugField(help_text='Masalan: chevrolet-spark', max_length=100, unique=True)),
                ('short_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('detail_title', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_summary', models.TextField(blank=True, null=True)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('benzin', 'Benzin'), ('gaz', 'Gaz'), ('gibrid', 'Gibrid'), ('elektro', 'Elektro')], default='benzin', max_length=20)),
                ('seats', models.PositiveIntegerField(default=5)),
                ('base_daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('slot', models.CharField(default='gallery_front', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.carmodel')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('color_name', models.CharField(max_length=50)),
                ('color_hex', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('hidden', 'Hidden')], default='available', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='districts.district')),
                ('model_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='cars.carmodel')),
            ],
        ),
    ]
