# Generated by Django 6.0.3 on 2026-04-01 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('benzin', 'Benzin'), ('gaz', 'Gaz'), ('gibrid', 'Gibrid'), ('elektro', 'Elektro')], max_length=20)),
                ('seats', models.PositiveIntegerField(default=5)),
                ('color', models.CharField(max_length=30)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('address', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('features', models.JSONField(default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='districts.district')),
            ],
        ),
    ]
