# Generated by Django 6.0.3 on 2026-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(default='sedan', max_length=50),
        ),
    ]
