# Generated by Django 6.0.3 on 2026-04-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
