# Generated by Django 5.2.1 on 2026-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_amenity_alter_car_id_alter_carimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='acceleration',
            field=models.CharField(blank=True, help_text='0-100 tezlanish (s)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='cargo_capacity',
            field=models.CharField(blank=True, help_text='Yukxona hajmi (masalan: 500 L)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='drive_type',
            field=models.CharField(blank=True, help_text='Privod (masalan: AWD, RWD)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine_type',
            field=models.CharField(blank=True, help_text='Dvigatel turi (masalan: V8 Biturbo)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='fuel_consumption',
            field=models.CharField(blank=True, help_text="Yoqilg'i sarfi (L/100km or kWh/100km)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='interior_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='interior_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='power',
            field=models.PositiveIntegerField(blank=True, help_text='Ot kuchi (HP/OT)', null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rear_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rear_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='top_speed',
            field=models.PositiveIntegerField(blank=True, help_text='Maksimal tezlik (km/h)', null=True),
        ),
    ]
