# Generated by Django 6.0.3 on 2026-04-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
