# Generated by Django 6.0.3 on 2026-04-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_maintenancerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['-id']},
        ),
    ]
