# Generated by Django 6.0.4 on 2026-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_options_alter_carmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='name_en',
            field=models.CharField(help_text='Masalan: Panorama', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_ru',
            field=models.CharField(help_text='Masalan: Panorama', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_uz',
            field=models.CharField(help_text='Masalan: Panorama', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='detail_summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='detail_summary_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='detail_summary_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='detail_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='detail_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='detail_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='interior_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='interior_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='interior_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='interior_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='interior_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='interior_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rear_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rear_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rear_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rear_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rear_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rear_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='short_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='short_tagline_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='short_tagline_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='short_tagline_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
