"""RIDELUX — Full 33 Car Model Definitions with real-world specs."""

CAR_DEFINITIONS = {
    "bmw-ix": {
        "brand": "BMW", "model_name": "iX xDrive50", "category": "elektro",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 5,
        "base_daily_price": 1200000, "base_deposit": 10000000, "allows_chauffeur": True,
        "short_tagline": "Kelajak Bugun — Nol Emissiya, Cheksiz Quvvat",
        "short_description": "523 km zaryad masofasi. Sustainably made — kelajak texnologiyasi bugun.",
        "detail_title": "BMW iX — Elektromobillar Dunyosida Yangi Davr",
        "detail_summary": "BMW iX xDrive50 modeli nafaqat elektr quvvati, balki barqaror rivojlanish falsafasini o'zida mujassam etgan. 523 ot kuchi va 765 Nm moment uni eng og'ir yo'llarda ham chaqqon qiladi. Harman Kardon audio tizimi va panorama lyuk sizga yuqori darajadagi qulaylikni taqdim etadi.",
        "power": 523, "top_speed": 200, "acceleration": "4.6s", "engine_type": "Dual Electric Motor",
        "fuel_consumption": "21.4 kWh/100km", "drive_type": "xDrive (AWD)", "cargo_capacity": "500 L",
        "rear_title": "FUTURISTIK PROFIL",
        "rear_description": "Avtomobilning orqa qismi o'zining minimalist va aerodinamik dizayni bilan ajralib turadi. Innovatsion LED chiroqlar va diffuzor havoni boshqarishda yordam beradi.",
        "interior_title": "SHAYNAM VA KENG SALON",
        "interior_description": "Interyerda qayta ishlangan materiallar va yuqori sifatli nappa charm ishlatilgan. 12.3 dyuymli kavisli ekran barcha boshqaruv elementlarini bir joyda jamlaydi.",
        "colors": [("Sophisto Grey", "#6b6b6b"), ("Mineral White", "#e8e8e4")],
        "amenities": ["panorama", "wireless_charging", "apple_carplay", "360_camera", "ambient_light"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Yakkasaroy"],
    },
    "bmw-m5-f90-cs": {
        "brand": "BMW", "model_name": "M5 F90 CS", "category": "premium",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 2875000, "base_deposit": 15000000, "allows_chauffeur": False,
        "short_tagline": "Track DNA, Street Legal — Yo'lda Bo'ronni His Eting",
        "short_description": "627 ot kuchi. M5 CS — seriyali ishlab chiqarishdagi eng kuchli BMW sedan.",
        "detail_title": "BMW M5 F90 CS — Tezlik va Quvvatning Cho'qqisi",
        "detail_summary": "M5 CS modeli sport avtomobillari ishqibozlari uchun maxsus yaratilgan. 4.4 litrli V8 Biturbo dvigateli sizga 3 soniyada 100 km/h tezlikka erishish imkonini beradi. Carbon fiber detallar va 'Gold Bronze' bezaklari bilan u ko'chalarda status belgisi bo'lib xizmat qiladi.",
        "power": 627, "top_speed": 305, "acceleration": "3.0s", "engine_type": "4.4L V8 Biturbo",
        "fuel_consumption": "11.3 L/100km", "drive_type": "M xDrive (AWD)", "cargo_capacity": "530 L",
        "rear_title": "DINAMIK ORQA PROFIL",
        "rear_description": "To'rt tomonlama sport ekzoz tizimi va uglerod tolali orqa diffuzor avtomobilning agressiv xarakterini ko'rsatib turadi.",
        "interior_title": "M SPORT SALON",
        "interior_description": "Salonda M Carbon o'rindiqlar va Alcantara qoplamalari hukmronlik qiladi. Har bir tikuv va detal haydovchini poyga muhitiga sho'ng'itish uchun mo'ljallangan.",
        "colors": [("Frozen Dark Grey", "#2a2a2a"), ("Le Mans Blue", "#003399")],
        "amenities": ["sport_seats", "heads_up_display", "apple_carplay", "launch_control"],
        "year_range": (2021, 2023), "districts": ["Chilonzor", "Mirobod"],
    },
    "bmw-x7-m60i": {
        "brand": "BMW", "model_name": "X7 M60i", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 7,
        "base_daily_price": 3450000, "base_deposit": 20000000, "allows_chauffeur": True,
        "short_tagline": "Exclusive Collection — Kuch va Hashamatning Uyg'unligi",
        "short_description": "BMW X7 M60i — premium SUV segmentining cho'qqisi. 530 ot kuchi.",
        "detail_title": "BMW X7 M60i — Haqiqiy Birinchi Klass SUV",
        "detail_summary": "7 kishilik keng salon va 530 ot kuchiga ega V8 dvigateli X7 M60i modelini oilaviy sayohatlar va biznes transferlar uchun ideal qiladi. Bowers & Wilkins audio tizimi har bir sayohatingizni koncert zaliga aylantiradi.",
        "power": 530, "top_speed": 250, "acceleration": "4.7s", "engine_type": "4.4L V8 Biturbo",
        "fuel_consumption": "12.9 L/100km", "drive_type": "xDrive (AWD)", "cargo_capacity": "750 L",
        "rear_title": "MOXIRLIK STANDARTI",
        "rear_description": "Katta o'lchamli SUV bo'lishiga qaramay, uning orqa qismi o'ta zamonaviy va ixcham ko'rinadi.",
        "interior_title": "BIRINCHI KLASS KOMFORT",
        "interior_description": "Individual iqlim nazorati, massaj funksiyasiga ega o'rindiqlar va eng yuqori sifatli charm qoplamalar har bir yo'lovchiga VIP darajadagi xizmatni ta'minlaydi.",
        "colors": [("Carbon Black", "#1a1a1a"), ("Alpine White", "#f5f5f0")],
        "amenities": ["panorama", "heated_seats", "360_camera", "massage", "apple_carplay", "heads_up_display"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Mirzo Ulug'bek"],
    },
    "byd-atto-3": {
        "brand": "BYD", "model_name": "Atto 3", "category": "elektro",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 5,
        "base_daily_price": 700000, "base_deposit": 4000000, "allows_chauffeur": False,
        "short_tagline": "Elektr SUV — Kelajak Bugun Yetib Keldi",
        "short_description": "Blade Battery texnologiyasi va 420 km zaryad masofasi.",
        "detail_title": "BYD Atto 3 — Zamonaviy va Tejamkor Elektro-SUV",
        "detail_summary": "Atto 3 modeli shahar va shahar atrofidagi sayohatlar uchun mukammal yechimdir. Blade Battery texnologiyasi xavfsizlik va uzoq umr ko'rishni kafolatlaydi, 12.8 dyuymli aylanuvchi ekran esa multimedia imkoniyatlarini kengaytiradi.",
        "power": 201, "top_speed": 160, "acceleration": "7.3s", "engine_type": "Single Motor Electric",
        "fuel_consumption": "15.6 kWh/100km", "drive_type": "FWD", "cargo_capacity": "440 L",
        "rear_title": "ZAMONAVIY ESTETIKA",
        "rear_description": "Avtomobilning orqa qismi sodda, ammo mazmunli chiziqlari bilan ajralib turadi. LED yoritish tizimi butun kenglik bo'ylab cho'zilgan.",
        "interior_title": "GYM INSPIRED DESIGN",
        "interior_description": "Interyer dizayni fitnes va musiqa olamidan ilhomlangan. Gitara torlarini eslatuvchi eshik detallari va sportiv o'rindiqlar yosh haydovchilar uchun mo'ljallangan.",
        "colors": [("Surf Blue", "#1a6699"), ("Winter White", "#f5f5f0")],
        "amenities": ["apple_carplay", "wireless_charging", "360_camera", "ambient_light"],
        "year_range": (2023, 2024), "districts": ["Yunusobod", "Yakkasaroy"],
    },
    "byd-chazor": {
        "brand": "BYD", "model_name": "Chazor", "category": "elektro",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 5,
        "base_daily_price": 550000, "base_deposit": 3000000, "allows_chauffeur": False,
        "short_tagline": "O'zbek Bozori Uchun Elektromobil",
        "short_description": "400 km zaryad masofasi va keng salon.",
        "detail_title": "BYD Chazor — O'zbek Yo'llarining Yangi Baxti",
        "detail_summary": "O'zbekiston iqlimi va sharoitiga moslashtirilgan BYD Chazor modeli tejamkorlik va qulaylik uyg'unligidir. 400 km zaryad masofasi kundalik ehtiyojlar uchun yetarli.",
        "power": 197, "top_speed": 170, "acceleration": "7.3s", "engine_type": "Single Motor Electric",
        "fuel_consumption": "16.5 kWh/100km", "drive_type": "FWD", "cargo_capacity": "450 L",
        "rear_title": "KLASSIK SEDAN",
        "rear_description": "Klassik sedan dizayni orqa tomondan barqarorlik va ishonchlilik hissiyotini beradi.",
        "interior_title": "SMART INTERYER",
        "interior_description": "Multimedia tizimi markazida joylashgan aylanuvchi ekran va zamonaviy datchiklar boshqaruvni osonlashtiradi.",
        "colors": [("Cosmos Black", "#111"), ("Snow White", "#f5f5f0")],
        "amenities": ["apple_carplay", "wireless_charging", "360_camera"],
        "year_range": (2023, 2024), "districts": ["Chilonzor", "Olmazor"],
    },
    "byd-han": {
        "brand": "BYD", "model_name": "Han EV", "category": "elektro",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 5,
        "base_daily_price": 900000, "base_deposit": 6000000, "allows_chauffeur": True,
        "short_tagline": "Dragon Face Design — O'ziga xos, Kuchli, Premium",
        "short_description": "517 ot kuchi AWD va 0-100 km/h 3.9 sek.",
        "detail_title": "BYD Han EV — Hashamatli Elektr Flagmani",
        "detail_summary": "Han EV modeli BYD kompaniyasining eng premium segmentdagi vakilidir. 517 ot kuchi va to'liq uzatma (AWD) uni haqiqiy yo'l yo'lbarsiga aylantiradi. Dynaudio audio tizimi va massaj o'rindiqlari biznes klass darajasini ta'minlaydi.",
        "power": 517, "top_speed": 185, "acceleration": "3.9s", "engine_type": "Dual Motor Electric",
        "fuel_consumption": "18.5 kWh/100km", "drive_type": "AWD", "cargo_capacity": "410 L",
        "rear_title": "PREMIUM FLAGSHIP",
        "rear_description": "Dragon Face dizayn falsafasi orqa qismda ham yaqqol namoyon bo'ladi. Yaxlit LED panel va sportiv aerodinamik qanotlar avtomobilning o'ziga xos qiyofasini yaratadi.",
        "interior_title": "LYUKS VA TEXNOLOGIYA",
        "interior_description": "Nappa charm, Dynaudio 12-dinamikli audio tizimi va VIP yo'lovchilar uchun maxsus funksiyalar.",
        "colors": [("Han Blue", "#001f5e"), ("Cinnabar Red", "#8b1a1a")],
        "amenities": ["panorama", "massage", "ambient_light", "apple_carplay", "heated_seats"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Mirzo Ulug'bek"],
    },
    "byd-seal": {
        "brand": "BYD", "model_name": "Seal", "category": "elektro",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 5,
        "base_daily_price": 850000, "base_deposit": 5000000, "allows_chauffeur": False,
        "short_tagline": "Ocean X Design — Dinamik va Innovatsion",
        "short_description": "Sportiv elektr sedan, CTB texnologiyasi bilan.",
        "detail_title": "BYD Seal — Tezkor va Aerodinamik Elektr Sedan",
        "detail_summary": "Seal modeli o'zining ultra-past qarshilik koeffitsiyenti (0.219 Cd) bilan hayratda qoldiradi. iTAC tizimi orqali aqlli boshqaruv sizga har qanday burilishda ishonch beradi.",
        "power": 530, "top_speed": 180, "acceleration": "3.8s", "engine_type": "Dual Motor Electric",
        "fuel_consumption": "18.2 kWh/100km", "drive_type": "AWD", "cargo_capacity": "450 L",
        "rear_title": "OCEAN X ESTETIKASI",
        "rear_description": "Orqa qism dizayni dengiz to'lqinlarini eslatadi. Dinamik chiroqlar va diffuzor sportivligini ta'kidlaydi.",
        "interior_title": "MINIMALIST LUXURY",
        "interior_description": "Markaziy konsolda kristall uzatmalar qutisi va 15.6 dyuymli ulkan aylanuvchi ekran joylashgan.",
        "colors": [("Aurora White", "#f0f0f0"), ("Atlantis Grey", "#4a4a4a")],
        "amenities": ["panorama", "sport_seats", "wireless_charging", "360_camera"],
        "year_range": (2023, 2024), "districts": ["Mirobod", "Yakkasaroy"],
    },
    "byd-song-plus": {
        "brand": "BYD", "model_name": "Song Plus", "category": "suv",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 5,
        "base_daily_price": 750000, "base_deposit": 4500000, "allows_chauffeur": False,
        "short_tagline": "Oila Uchun Mukammal SUV",
        "short_description": "Keng salon, yuqori xavfsizlik va zamonaviy interyer.",
        "detail_title": "BYD Song Plus — Oilaviy Krossoverning Yangi Me'yori",
        "detail_summary": "Song Plus o'zida SUV segmentining barcha qulayliklarini jamlagan. Keng salon, baland klirens va tejamkor elektr yuritmalar uni oilaviy sayohatlar uchun eng yaxshi tanlovga aylantiradi.",
        "power": 197, "top_speed": 170, "acceleration": "7.8s", "engine_type": "Single Motor Electric",
        "fuel_consumption": "17.5 kWh/100km", "drive_type": "FWD", "cargo_capacity": "510 L",
        "rear_title": "KENG VA BARQAROR",
        "rear_description": "Orqa tarafdan Song Plus o'zining salobati bilan ajralib turadi. Kengaytirilgan yo'l izi va LED chiroqlar zamonaviy ko'rinish beradi.",
        "interior_title": "OILAVIY KOMFORT",
        "interior_description": "Orqa qatorda oyoqlar uchun juda keng joy, yumshoq nappa charm va iqlim nazorati komfortni yuqori darajaga ko'taradi.",
        "colors": [("Time Grey", "#555555"), ("Snow White", "#ffffff")],
        "amenities": ["panorama", "heated_seats", "360_camera", "apple_carplay"],
        "year_range": (2023, 2024), "districts": ["Chilonzor", "Sergeli"],
    },
    "chevrolet-cobalt": {
        "brand": "Chevrolet", "model_name": "Cobalt", "category": "sedan",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 350000, "base_deposit": 1500000, "allows_chauffeur": False,
        "short_tagline": "Xalq Tanlovi — Ishonchli va Hamyonbop",
        "short_description": "O'zbekistonning eng mashhur sedani, keng yukxona.",
        "detail_title": "Chevrolet Cobalt — Har Kun Uchun Ishonchli Hamroh",
        "detail_summary": "Cobalt modeli o'zining tejamkorligi va chidamliligi bilan tanilgan. Katta yukxona (563 litr) uni ayniqsa bozor va oilaviy yumushlar uchun ajralmas qiladi. Oddiy, ammo samarali texnologiyalar uzoq yillar xizmat qiladi.",
        "power": 105, "top_speed": 170, "acceleration": "11.7s", "engine_type": "1.5L Inline-4",
        "fuel_consumption": "6.7 L/100km", "drive_type": "FWD", "cargo_capacity": "563 L",
        "rear_title": "UXCHAM VA AMALIY",
        "rear_description": "Orqa dizayn bu modelning amaliyligini ta'kidlaydi. Keng yukxona qopqog'i va baland chiroqlar yuk yuklashni osonlashtiradi.",
        "interior_title": "ERGONOMIK SALON",
        "interior_description": "Interyerda soddalik va funksionallikka urg'u berilgan. O'rindiqlar uzoq masofalarda haydovchi charchamasligi uchun sozlangan.",
        "colors": [("Qora", "#111"), ("Oq", "#ffffff")],
        "amenities": ["apple_carplay"],
        "year_range": (2021, 2024), "districts": ["Chilonzor", "Olmazor", "Uchtepa"],
    },
    "chevrolet-gentra": {
        "brand": "Chevrolet", "model_name": "Gentra", "category": "sedan",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 350000, "base_deposit": 1500000, "allows_chauffeur": False,
        "short_tagline": "Klassika — Biznes va Kundalik Sayohat",
        "short_description": "Yumshoq yurish va qulay salon bilan tanilgan.",
        "detail_title": "Chevrolet Gentra — Yumshoqlik va Klassik Dizayn",
        "detail_summary": "Gentra o'zbek haydovchilari orasida o'zining yumshoq kalti va qulay o'rindiqlari bilan afsonaga aylangan. Lyukli va ABS tizimli yuqori pozitsiyalar shaharda ham ishonch beradi.",
        "power": 107, "top_speed": 180, "acceleration": "12.5s", "engine_type": "1.5L Inline-4",
        "fuel_consumption": "7.5 L/100km", "drive_type": "FWD", "cargo_capacity": "400 L",
        "rear_title": "KLASSIK SILUET",
        "rear_description": "Klassik sedan shakllari va mustahkam osma tizimi avtomobilning umrboqligidan dalolat beradi.",
        "interior_title": "QULAY INTERYER",
        "interior_description": "Salon materiallari yumshoq va ko'zga yoqimli. Lyuk orqali kirayotgan quyosh nuri sayohatni yanada zavqli qiladi.",
        "colors": [("Qora", "#111"), ("Oq", "#ffffff"), ("Kulrang", "#808080")],
        "amenities": ["panorama", "heated_seats"],
        "year_range": (2022, 2024), "districts": ["Sergeli", "Yashnobod"],
    },
    "chevrolet-malibu-2": {
        "brand": "Chevrolet", "model_name": "Malibu 2", "category": "premium",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 750000, "base_deposit": 4000000, "allows_chauffeur": True,
        "short_tagline": "Business Executive — Kuchli va Elegant",
        "short_description": "2.0 Turbo dvigatel, 253 ot kuchi. Premium komfort.",
        "detail_title": "Chevrolet Malibu 2 — Biznes Olami Uchun Dinamika",
        "detail_summary": "Malibu 2 modeli o'zida 2.0 litrli turbo dvigatel quvvati va biznes klass hashamatini jamlagan. 253 ot kuchi sizga har qanday vaziyatda birinchi bo'lishni ta'minlaydi. Bose audio tizimi va nappa charm o'rindiqlar haqiqiy rohat beradi.",
        "power": 253, "top_speed": 210, "acceleration": "6.3s", "engine_type": "2.0L Turbo Inline-4",
        "fuel_consumption": "8.5 L/100km", "drive_type": "FWD", "cargo_capacity": "447 L",
        "rear_title": "ELEGANTSLIK RAMZI",
        "rear_description": "Dinamik LED chiroqlar va sportiv shakllar uning biznes klass ekanligini ta'kidlaydi.",
        "interior_title": "BIZNES KLASS KOMFORT",
        "interior_description": "Salon nappa charm bilan qoplangan. Smart infotainment tizimi smartfoningiz bilan to'liq integratsiyalashadi.",
        "colors": [("Qora", "#0a0a0a"), ("Oq Pearl", "#f8f8f8")],
        "amenities": ["panorama", "heated_seats", "apple_carplay", "ambient_light", "wireless_charging"],
        "year_range": (2021, 2023), "districts": ["Mirobod", "Yunusobod"],
    },
    "chevrolet-malibu_1": {
        "brand": "Chevrolet", "model_name": "Malibu 1", "category": "sedan",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 400000, "base_deposit": 2000000, "allows_chauffeur": False,
        "short_tagline": "Amerika Ruhi — Uzun va Barqaror",
        "short_description": "Katta o'lchamli sedan, yuqori komfort darajasi.",
        "detail_title": "Chevrolet Malibu 1 — Klassik Amerika Sedani",
        "detail_summary": "Malibu 1 o'zining og'ir va bosiq harakati bilan tanilgan. 2.4 litrli atmosferik dvigatel ishonchlilikni kafolatlaydi, keng g'ildirak bazasi yo'ldagi notekisliklarni maksimal darajada yutadi.",
        "power": 167, "top_speed": 195, "acceleration": "9.5s", "engine_type": "2.4L Inline-4",
        "fuel_consumption": "9.2 L/100km", "drive_type": "FWD", "cargo_capacity": "462 L",
        "rear_title": "BARQARORLIK VA SHAKL",
        "rear_description": "Kuzovning mustahkamligi va Amerika sedanlariga xos orqa dizayn unga joziba bag'ishlaydi.",
        "interior_title": "KLASSIK AMERIKA",
        "interior_description": "Keng va yumshoq o'rindiqlar sizni quchoqlab oladi. Ovoz izolyatsiyasi o'z sinfidagi eng yaxshilaridan biri.",
        "colors": [("Black", "#111"), ("Silver", "#c0c0c0")],
        "amenities": ["heated_seats"],
        "year_range": (2015, 2018), "districts": ["Chilonzor", "Uchtepa"],
    },
    "chevrolet-onix": {
        "brand": "Chevrolet", "model_name": "Onix", "category": "sedan",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 450000, "base_deposit": 2500000, "allows_chauffeur": False,
        "short_tagline": "Smart Sedan — Yangi Avlod Texnologiyasi",
        "short_description": "Turbo dvigatel, kam yoqilg'i sarfi va zamonaviy xavfsizlik.",
        "detail_title": "Chevrolet Onix — Shahar Hayotiga Moslashgan Smart Sedan",
        "detail_summary": "Onix modeli yangi avlod avtomobili bo'lib, u tejamkor turbo motor va aqlli texnologiyalarni birlashtiradi. Avtomatik parkovka tizimi va kor ko'rinish zonalari datchiklari shaharda juda asqotadi.",
        "power": 132, "top_speed": 190, "acceleration": "10.9s", "engine_type": "1.2L Turbo Inline-3",
        "fuel_consumption": "5.9 L/100km", "drive_type": "FWD", "cargo_capacity": "469 L",
        "rear_title": "DINAMIK VA IXCHAM",
        "rear_description": "Ixcham orqa dizayn sportiv ruh va amaliylikni uyg'unlashtiradi. LED chiroqlar zamonaviy qiyofa bag'ishlaydi.",
        "interior_title": "SMART TEXNOLOGIYA",
        "interior_description": "Raqamli asboblar paneli, sensorli multimedia va kalitsiz kirish. Wireless charging moduli telefoningizni simsiz quvvatlaydi.",
        "colors": [("Dark Grey", "#333"), ("White", "#fff")],
        "amenities": ["apple_carplay", "wireless_charging", "360_camera"],
        "year_range": (2023, 2024), "districts": ["Yunusobod", "Shayxontohur"],
    },
    "chevrolet-spark": {
        "brand": "Chevrolet", "model_name": "Spark", "category": "economy",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 250000, "base_deposit": 1000000, "allows_chauffeur": False,
        "short_tagline": "Shahar Uchun Yaratilgan — Arzon va Chaqqon",
        "short_description": "Tor ko'chalarda moslashuvchan, yoqilg'i sarfi minimal.",
        "detail_title": "Chevrolet Spark — Kichik, Ammo Chaqqon Va Tejamkor",
        "detail_summary": "Spark shahar tirbandliklarida eng yaxshi do'stingizdir. Kichik o'lchamlari tufayli parkovka muammo emas, tejamkor motori hamyoningizni asraydi. Yoshlar va yangi haydovchilar uchun ideal.",
        "power": 85, "top_speed": 160, "acceleration": "13.5s", "engine_type": "1.25L Inline-4",
        "fuel_consumption": "5.5 L/100km", "drive_type": "FWD", "cargo_capacity": "170 L",
        "rear_title": "IXCHAM VA CHAQQON",
        "rear_description": "Orqa qism uning funksionalligini ko'rsatadi. Eshik tutqichlarining yashirin joylashishi sportiv ko'rinish beradi.",
        "interior_title": "YOSH VA DINAMIK",
        "interior_description": "Mototsikl uslubidagi spidometr va yorqin rangli interyer detallari ruhni ko'taradi.",
        "colors": [("White", "#ffffff"), ("Silver", "#a8a8a8"), ("Red", "#cc2200")],
        "amenities": ["apple_carplay"],
        "year_range": (2021, 2024), "districts": ["Chilonzor", "Sergeli", "Yashnobod"],
    },
    "chevrolet-tahoe": {
        "brand": "Chevrolet", "model_name": "Tahoe", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 8,
        "base_daily_price": 2000000, "base_deposit": 10000000, "allows_chauffeur": True,
        "short_tagline": "Amerika Afsonasi — Keng va Kuchli",
        "short_description": "355 ot kuchi, 8 o'rindiq. Oilaviy va VIP transfer uchun.",
        "detail_title": "Chevrolet Tahoe — Ulkan Quvvat va Cheksiz Kenglik",
        "detail_summary": "Tahoe modeli yo'llarning qirolidir. V8 dvigateli va 8 kishilik keng salon har qanday oilaviy sayohatni birinchi klass darajasiga ko'taradi. RST Edition dizayni bilan siz doim e'tibor markazida bo'lasiz.",
        "power": 355, "top_speed": 180, "acceleration": "7.5s", "engine_type": "5.3L V8",
        "fuel_consumption": "14.5 L/100km", "drive_type": "4WD", "cargo_capacity": "722 L",
        "rear_title": "KUCHLI AMERIKANES",
        "rear_description": "Mustahkam kvadratik shakllar va massiv orqa profil avtomobilning barqarorligidan dalolat beradi.",
        "interior_title": "GIGANT SALON",
        "interior_description": "8 kishigacha qulay joylashuv, Bose audio va uch zonali iqlim nazorati. O'rindiqlarni yig'ish orqali yukxonani ulkan maydonga aylantirish mumkin.",
        "colors": [("Black", "#0a0a0a"), ("Summit White", "#f8f8f6")],
        "amenities": ["panorama", "heated_seats", "apple_carplay", "360_camera", "wireless_charging"],
        "year_range": (2021, 2023), "districts": ["Chilonzor", "Uchtepa"],
    },
    "chevrolet-tracker-2": {
        "brand": "Chevrolet", "model_name": "Tracker 2", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 450000, "base_deposit": 2500000, "allows_chauffeur": False,
        "short_tagline": "Yilning SUV'i — Zamonaviy va Qulay",
        "short_description": "Kompakt SUV, Redline dizayni bilan ajralib turadi.",
        "detail_title": "Chevrolet Tracker 2 — Kompakt Krossoverning Mukammal Namunasi",
        "detail_summary": "Tracker 2 shaharda baland klirens va ixchamlikni qadrlaydiganlar uchun yaratilgan. Panorama lyuk va zamonaviy turbo motor kayfiyatni ko'taradi. Redline detallari sportiv ruh beradi.",
        "power": 137, "top_speed": 185, "acceleration": "10.5s", "engine_type": "1.2L Turbo Inline-3",
        "fuel_consumption": "6.5 L/100km", "drive_type": "FWD", "cargo_capacity": "393 L",
        "rear_title": "SPORTIV VA COMPACT",
        "rear_description": "Orqa chiziqlar aerodinamik qismlari va Redline logotiplari bilan ajralib turadi.",
        "interior_title": "TEXNOLOGIK INTERYER",
        "interior_description": "Multimedia tizimi MyLink orqali barcha funksiyalar markazlashgan, asboblar paneli o'ta o'qilishi oson.",
        "colors": [("Dark Grey", "#222"), ("White", "#fff")],
        "amenities": ["panorama", "apple_carplay", "wireless_charging"],
        "year_range": (2023, 2024), "districts": ["Yunusobod", "Mirobod"],
    },
    "chevrolet-traverse": {
        "brand": "Chevrolet", "model_name": "Traverse", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 7,
        "base_daily_price": 1500000, "base_deposit": 8000000, "allows_chauffeur": True,
        "short_tagline": "Oila bilan Sayohat — Katta va Xavfsiz",
        "short_description": "V6 dvigatel, 7 kishilik keng salon va AWD.",
        "detail_title": "Chevrolet Traverse — Oilaviy Krossoverlar Podshohi",
        "detail_summary": "Traverse modeli oilangiz a'zolari uchun maksimal xavfsizlik va qulaylikni taklif etadi. 3.6 litrli V6 dvigateli har qanday yuk bilan ishonchli harakatlanadi. Uchinchi qator o'rindiqlari to'liq o'lchamli.",
        "power": 281, "top_speed": 190, "acceleration": "7.8s", "engine_type": "3.6L V6",
        "fuel_consumption": "11.5 L/100km", "drive_type": "AWD", "cargo_capacity": "651 L",
        "rear_title": "GIGANT OILAVIY SUV",
        "rear_description": "Orqa profil avtomobilning keng va salobatli ekanligini isbotlaydi. Katta LED optika premium ko'rinish bag'ishlaydi.",
        "interior_title": "PREMIER KLASS KOMFORT",
        "interior_description": "Premier darajasidagi charm va plastik. Adaptiv kruiz kontrol va 3-zonali iqlim nazorati har bir yo'lovchiga o'z komfort zonasini yaratadi.",
        "colors": [("Black", "#111"), ("White", "#fdfdfd")],
        "amenities": ["panorama", "heated_seats", "apple_carplay", "360_camera"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Mirzo Ulug'bek"],
    },
    "hyundai-santa-fe": {
        "brand": "Hyundai", "model_name": "Santa Fe", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 7,
        "base_daily_price": 1000000, "base_deposit": 5000000, "allows_chauffeur": True,
        "short_tagline": "Komfort Cho'qqisi — Yuqori Texnologiyali SUV",
        "short_description": "Premium interyer va ravon harakatlanish ustuvorligi.",
        "detail_title": "Hyundai Santa Fe — Hashamat va Amaliylik Uyg'unligi",
        "detail_summary": "Santa Fe o'zida Koreya muhandisligi durdonalarini jamlagan. HTRAC to'liq uzatma tizimi har qanday ob-havoda yo'lni ushlashni kafolatlaydi, Calligraphy komplektatsiyasi nappa charm va Harman Kardon audio bilan siylaydi.",
        "power": 281, "top_speed": 210, "acceleration": "7.0s", "engine_type": "2.5L Turbo Smartstream",
        "fuel_consumption": "9.5 L/100km", "drive_type": "HTRAC (AWD)", "cargo_capacity": "634 L",
        "rear_title": "SALOBATLI SUV",
        "rear_description": "Yaxlit chiziqli LED chiroqlar va dinamik shakllar Santa Fe ga yo'llarda ajralib turadigan ko'rinish beradi.",
        "interior_title": "CALLIGRAPHY LUXURY",
        "interior_description": "Barcha detallar qo'lda ishlangan kabi sifatli. Markaziy konsolda tugmalar boshqaruvni osonlashtiradi.",
        "colors": [("Taiga Brown", "#4b3a2a"), ("Abyss Black", "#050505")],
        "amenities": ["panorama", "massage", "heated_seats", "360_camera", "wireless_charging"],
        "year_range": (2023, 2024), "districts": ["Mirobod", "Yunusobod"],
    },
    "hyundai-sonata": {
        "brand": "Hyundai", "model_name": "Sonata", "category": "sedan",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 700000, "base_deposit": 4000000, "allows_chauffeur": True,
        "short_tagline": "Business Class — Ish uchrashuvlari uchun ideal",
        "short_description": "Aerodinamik dizayn va executive interior.",
        "detail_title": "Hyundai Sonata — Sportiv Dizayn va Biznes Komfort",
        "detail_summary": "Yangi Sonata (DN8) modeli o'zining jasur dizayni bilan ajralib turadi. Kapot qismidan boshlanuvchi LED chiroqlar unga o'zgacha joziba beradi. Keng salon va yumshoq yurish biznes klass haydovchilari uchun ayni muddao.",
        "power": 191, "top_speed": 210, "acceleration": "8.8s", "engine_type": "2.5L GDI Inline-4",
        "fuel_consumption": "7.8 L/100km", "drive_type": "FWD", "cargo_capacity": "453 L",
        "rear_title": "AERODINAMIK SEDAN",
        "rear_description": "Fastback uslubidagi orqa qism va murakkab geometriyali chiroqlar avtoprogressivlik belgisidir.",
        "interior_title": "EXECUTIVE SALON",
        "interior_description": "Shift-by-wire texnologiyasi orqali uzatmalarni tugmalar orqali boshqarish mumkin. 12.3 dyuymli raqamli displey futuristik tarzda ko'rsatadi.",
        "colors": [("Phantom Black", "#111"), ("Quartz White", "#f0f0ec")],
        "amenities": ["apple_carplay", "heated_seats", "wireless_charging", "ambient_light", "360_camera"],
        "year_range": (2021, 2023), "districts": ["Yunusobod", "Chilonzor"],
    },
    "hyundai-tucson": {
        "brand": "Hyundai", "model_name": "Tucson", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 750000, "base_deposit": 4500000, "allows_chauffeur": False,
        "short_tagline": "Parametric Design — Ko'z Bog'lovchi Tashqi Ko'rinish",
        "short_description": "4-avlod Tucson, innovatsion LED chiroqlar bilan.",
        "detail_title": "Hyundai Tucson — Parametrik Dinamika va Kelajak Dizayni",
        "detail_summary": "Yangi Tucson (NX4) o'zining 'jasur parametrik' dizayni bilan diqqatni tortadi. Radiator panjarasining bir qismi bo'lgan LED chiroqlar uni hech biri bilan adashtirib bo'lmaydigan qildi. Smartstream dvigateli va AWD tizimi ishonchni oshiradi.",
        "power": 187, "top_speed": 200, "acceleration": "9.1s", "engine_type": "2.5L Smartstream",
        "fuel_consumption": "8.2 L/100km", "drive_type": "AWD", "cargo_capacity": "539 L",
        "rear_title": "PARAMETRIK DINAMIKA",
        "rear_description": "Yirtqich hayvon tishlarini eslatuvchi orqa chiroqlar Tucson ga yirtqichlik va sportivlik bag'ishlaydi.",
        "interior_title": "INTERSPACE KOMFORT",
        "interior_description": "Vertikal ekran va ochiq asboblar paneli salonda erkinlik va texnologiya hissini beradi.",
        "colors": [("Shimmering Silver", "#c5c5c5"), ("Abyss Black", "#0a0a0a")],
        "amenities": ["panorama", "apple_carplay", "wireless_charging", "heated_seats", "360_camera"],
        "year_range": (2021, 2024), "districts": ["Yunusobod", "Mirzo Ulug'bek"],
    },
    "kia-carnival": {
        "brand": "Kia", "model_name": "Carnival", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 7,
        "base_daily_price": 1200000, "base_deposit": 6000000, "allows_chauffeur": True,
        "short_tagline": "Grand Utility Vehicle — VIP Sayohat Standarti",
        "short_description": "7 kishilik VIP salon, biznes klass qulayligi.",
        "detail_title": "Kia Carnival — Yer Ustidagi Birinchi Klass Layneri",
        "detail_summary": "Carnival oddiy minivan emas, bu Grand Utility Vehicle. 7 kishilik VIP kursi yo'lovchilarga to'liq yotish holatiga o'tish imkonini beradi. Bose audio va panorama lyuklar har bir sayohatni bayramga aylantiradi.",
        "power": 290, "top_speed": 190, "acceleration": "7.0s", "engine_type": "3.5L V6 GDI",
        "fuel_consumption": "12.5 L/100km", "drive_type": "FWD", "cargo_capacity": "627 L",
        "rear_title": "GRAND UTILITY",
        "rear_description": "Mashinaning orqa dizayni uning ulkan qudratini va amaliyligini ko'rsatadi.",
        "interior_title": "VIP LOUNGE",
        "interior_description": "Premium o'rindiqlar massaj va ventilyatsiya bilan jihozlangan. Har bir yo'lovchi uchun shaxsiy USB portlar va iqlim nazorati.",
        "colors": [("Aurora Black Pearl", "#0f0f0f"), ("Panthera Metal", "#3b3b3b")],
        "amenities": ["panorama", "massage", "heated_seats", "360_camera", "wireless_charging"],
        "year_range": (2022, 2024), "districts": ["Mirobod", "Yunusobod"],
    },
    "kia-ev6": {
        "brand": "Kia", "model_name": "EV6", "category": "elektro",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 5,
        "base_daily_price": 950000, "base_deposit": 6000000, "allows_chauffeur": False,
        "short_tagline": "Electric Performance — Dinamik Elektro-Krossover",
        "short_description": "Sport dizayn va 500+ km masofaga zaryad.",
        "detail_title": "Kia EV6 — Inqilobiy Elektr Dinamikasi",
        "detail_summary": "EV6 modeli Kia kompaniyasining elektr dunyosidagi yangi yuzidir. O'ta tez zaryad olish va 500 km dan ortiq masofa uni shaharlararo sayohat uchun ham ishonchli qiladi. 325 ot kuchi har qanday poyga tezlanishini beradi.",
        "power": 325, "top_speed": 185, "acceleration": "5.2s", "engine_type": "Dual Motor Electric",
        "fuel_consumption": "17.2 kWh/100km", "drive_type": "AWD", "cargo_capacity": "490 L",
        "rear_title": "DIGITAL TIGER DESIGN",
        "rear_description": "Orqa tarafdan EV6 kosmik kemadek ko'rinadi. Butun eni bo'ylab cho'zilgan LED chiroqlar uning imzosi hisoblanadi.",
        "interior_title": "EKOLOGIK VA SMART",
        "interior_description": "Qayta ishlangan ekologik materiallar ishlatilgan. AR gologramma displey navigatsiya ma'lumotlarini ko'zlaringiz qarshisida ko'rsatadi.",
        "colors": [("Yacht Blue", "#00205b"), ("Moonscape Grey", "#5a5a5a")],
        "amenities": ["panorama", "heads_up_display", "wireless_charging", "360_camera", "ambient_light"],
        "year_range": (2023, 2024), "districts": ["Yakkasaroy", "Yunusobod"],
    },
    "kia-k5": {
        "brand": "Kia", "model_name": "K5", "category": "sedan",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 650000, "base_deposit": 3500000, "allows_chauffeur": False,
        "short_tagline": "Dinamik Sedan — Sportiv Ruhiyatli Tashqi Ko'rinish",
        "short_description": "Mashhur 'Moshalka' chiroqlar va GT-Line dizayn.",
        "detail_title": "Kia K5 — Yosh va Jushqin Dil Sohiblari Uchun",
        "detail_summary": "K5 modeli 'yurak urishi' uslubidagi LED chiroqlari bilan darrov ko'zga tashlanadi. GT-Line sportiv paket avtomobilga agressivlik beradi, panoramali salon sayohatni zavqli qiladi.",
        "power": 191, "top_speed": 210, "acceleration": "7.8s", "engine_type": "2.5L GDI Inline-4",
        "fuel_consumption": "7.5 L/100km", "drive_type": "FWD", "cargo_capacity": "453 L",
        "rear_title": "FASTBACK PROFIL",
        "rear_description": "Fastback uslubidagi tom chizig'i avtomobilni qimmatroq ko'rsatadi. Uzluksiz chiziqli chiroqlar texnologik ekanligidan dalolat beradi.",
        "interior_title": "SPORTIV VA SMART",
        "interior_description": "Dashboard haydovchiga yo'naltirilgan, o'zingizni xuddi pilotdek his qilasiz. Sensorli boshqaruv paneli haydash zavqini oshiradi.",
        "colors": [("Interstellar Grey", "#444"), ("Snow White", "#fff")],
        "amenities": ["panorama", "apple_carplay", "wireless_charging", "ambient_light"],
        "year_range": (2022, 2024), "districts": ["Chilonzor", "Mirzo Ulug'bek"],
    },
    "kia-sonet": {
        "brand": "Kia", "model_name": "Sonet", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 450000, "base_deposit": 2500000, "allows_chauffeur": False,
        "short_tagline": "Shahar SUV'i — Ixcham va Zamonaviy",
        "short_description": "Yangi model, shahar ichida qulay SUV.",
        "detail_title": "Kia Sonet — Ixcham Shahar Krossoveri",
        "detail_summary": "Sonet yangi avlod krossoveri, ixcham o'lchamlar va premium funksiyalarni birlashtiradi. Ventilyatsiya qilinadigan o'rindiqlar va Bose audio o'z sinfidagi kamdan-kam avtomobillarda uchraydi.",
        "power": 115, "top_speed": 170, "acceleration": "11.5s", "engine_type": "1.5L Inline-4",
        "fuel_consumption": "7.0 L/100km", "drive_type": "FWD", "cargo_capacity": "392 L",
        "rear_title": "IXCHAM VA CHAQQON",
        "rear_description": "Soddalik va dinamika uyg'unligi. Sonet baland klirensi bilan ishonchli SUV taassurotini qoldiradi.",
        "interior_title": "KOMPAKT LUX",
        "interior_description": "Sifatli va chidamli materiallar. Bose premium audio har bir musiqa notasini tinniq yangratadi.",
        "colors": [("Beige", "#d2b48c"), ("Black", "#111")],
        "amenities": ["apple_carplay", "heated_seats", "wireless_charging"],
        "year_range": (2024, 2024), "districts": ["Shayxontohur", "Olmazor"],
    },
    "kia-sorento": {
        "brand": "Kia", "model_name": "Sorento", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 7,
        "base_daily_price": 950000, "base_deposit": 5000000, "allows_chauffeur": True,
        "short_tagline": "Katta Oila Sayohati — 7 Kishilik Isbotlangan Sifat",
        "short_description": "Ishonchli krossover, keng salon va AWD.",
        "detail_title": "Kia Sorento — Har Bir Safar Uchun Birinchi Klass",
        "detail_summary": "Sorento mukammal muvozanat. Keng salon, baland texnologiya va kuchli AWD tizimi uni shahar va qishloq yo'llarida birdek ishonchli qiladi. Nappa charm interyer hashamat hissini beradi.",
        "power": 281, "top_speed": 210, "acceleration": "7.5s", "engine_type": "2.5L Turbo GDI",
        "fuel_consumption": "9.8 L/100km", "drive_type": "AWD", "cargo_capacity": "616 L",
        "rear_title": "GIGANT OILAVIY KROSSOVER",
        "rear_description": "Vertikal LED orqa chiroqlar Sorento ga salobat bag'ishlaydi. Uzoq yillar xizmat qilishga tayyor.",
        "interior_title": "PREMIUM OILAVIY KOMFORT",
        "interior_description": "7 kishigacha bemalol sig'adigan salon, Bose audio va panoramali tom go'zal manzaralardan bahramand qiladi.",
        "colors": [("Mineral Blue", "#1a2a4a"), ("White Pearl", "#fdfdfd")],
        "amenities": ["panorama", "heated_seats", "apple_carplay", "360_camera", "wireless_charging"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Mirobod"],
    },
    "mercedes-g63": {
        "brand": "Mercedes-Benz", "model_name": "G63 AMG", "category": "premium",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 5000000, "base_deposit": 30000000, "allows_chauffeur": True,
        "short_tagline": "Afsonaviy Gelik — Kuch va Status Belgisi",
        "short_description": "V8 Biturbo, 585 ot kuchi. Off-road va shahar qiroli.",
        "detail_title": "Mercedes-Benz G63 AMG — Yo'llarning Mutlaq Qiroli",
        "detail_summary": "G63 AMG shunchaki avtomobil emas, bu statusning oliy ko'rinishidir. 585 ot kuchiga ega V8 Biturbo dvigatelining ovozi hayajon beradi. Har bir detal poyga DNA si bilan boyitilgan va hashamat cho'qqisiga olib chiqilgan.",
        "power": 585, "top_speed": 240, "acceleration": "4.5s", "engine_type": "4.0L V8 Biturbo",
        "fuel_consumption": "16.5 L/100km", "drive_type": "4MATIC (AWD)", "cargo_capacity": "667 L",
        "rear_title": "OFF-ROAD QUVVATI",
        "rear_description": "Zaxira g'ildiragi va kuchli orqa dizayn xarakterini ko'rsatadi. Har qanday off-road sharoitida birinchi bo'lishga tayyor.",
        "interior_title": "EXECUTIVE LUXURY",
        "interior_description": "IWC soati, Burmester surround system va qo'lda tikilgan nappa charm. Ikki 12.3 dyuymli ulkan ekran barcha texnologiyalarni jamlaydi.",
        "colors": [("Matte Black", "#0a0a0a"), ("Emerald Green", "#004d00")],
        "amenities": ["massage", "ambient_light", "360_camera", "apple_carplay", "sport_seats", "heads_up_display"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Mirobod"],
    },
    "mercedes-s-class-w223": {
        "brand": "Mercedes-Benz", "model_name": "S-Class W223", "category": "premium",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 4500000, "base_deposit": 25000000, "allows_chauffeur": True,
        "short_tagline": "Dunyodagi Eng Yaxshi Avtomobil — Hashamat Cho'qqisi",
        "short_description": "Maybach darajasidagi komfort, yangi W223 avlodi.",
        "detail_title": "Mercedes-Benz S-Class W223 — Mukammallik Standarti",
        "detail_summary": "Yangi S-Class dunyodagi eng ilg'or avtomobil. Digital Light chiroqlari, to'liq avtomatlashtirilgan tizimlar va mislsiz izolyatsiya. Biznes klass yo'lovchilari uchun mobil ofis va dam olish maskani.",
        "power": 429, "top_speed": 250, "acceleration": "4.9s", "engine_type": "3.0L Inline-6 Turbo + EQ Boost",
        "fuel_consumption": "9.5 L/100km", "drive_type": "4MATIC (AWD)", "cargo_capacity": "550 L",
        "rear_title": "HASHAMATLI PROFIL",
        "rear_description": "Yashirin eshik tutqichlari aerodinamikani yaxshilaydi va toza ko'rinish beradi. Orqa chiroqlar qimmatbaho kristallarni eslatadi.",
        "interior_title": "BIRINCHI KLASS SALON",
        "interior_description": "4D Burmester audio o'rindiqlardagi vibratsiya orqali musiqa chuqurligini his qildiradi. Executive massaj o'rindiqlari va OLED ekranlar.",
        "colors": [("Obsidian Black", "#010101"), ("Diamond White", "#f0f0f0")],
        "amenities": ["panorama", "massage", "ambient_light", "360_camera", "heads_up_display", "wireless_charging"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Yakkasaroy"],
    },
    "porsche-cayenne-coupe": {
        "brand": "Porsche", "model_name": "Cayenne Coupe", "category": "premium",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 3500000, "base_deposit": 20000000, "allows_chauffeur": True,
        "short_tagline": "Sport SUV — Porsche DNA si Har bir Detalda",
        "short_description": "Sportiv kupe dizayn va murosasiz dinamika.",
        "detail_title": "Porsche Cayenne Coupe — SUV shaklidagi Haqiqiy Sportkar",
        "detail_summary": "Cayenne Coupe sport avtomobili DNA sini SUV amaliyligi bilan birlashtirgan. Sport Chrono paketi va adaptiv pnevmatik osma tizimi har qanday burilishni hayajonli qiladi.",
        "power": 335, "top_speed": 245, "acceleration": "5.7s", "engine_type": "3.0L V6 Turbo",
        "fuel_consumption": "11.2 L/100km", "drive_type": "AWD", "cargo_capacity": "625 L",
        "rear_title": "FLYLINE DIZAYN",
        "rear_description": "Flyline dizayni dinamik kupe qiyofasini beradi. Porsche yoritish paneli butun kenglik bo'ylab cho'zilgan.",
        "interior_title": "SPORTIV HASHAMAT",
        "interior_description": "Porsche Advanced Cockpit barcha boshqaruvlarni barmoq uchingizda jamlaydi. Sportiv Merino charm o'rindiqlar tezkor haydashda ishonchli ushlab turadi.",
        "colors": [("Jet Black", "#0c0c0c"), ("Crayon", "#d0d0d0")],
        "amenities": ["panorama", "sport_seats", "heads_up_display", "360_camera", "apple_carplay"],
        "year_range": (2023, 2024), "districts": ["Yunusobod", "Mirobod"],
    },
    "porsche-taycan-turbo-s": {
        "brand": "Porsche", "model_name": "Taycan Turbo S", "category": "elektro",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 4,
        "base_daily_price": 4000000, "base_deposit": 25000000, "allows_chauffeur": False,
        "short_tagline": "Elektr Hayajon — 0 dan 100 gacha 2.8 Sekund",
        "short_description": "Dunyodagi eng tezkor elektr sedanlardan biri.",
        "detail_title": "Porsche Taycan Turbo S — Mutlaq Elektr Quvvati",
        "detail_summary": "Taycan Turbo S elektromobillar nimalarga qodir ekanligini isbotlaydi. 750 ot kuchi va 0-100 tezlanishni 2.8 soniyada amalga oshirish — yerdagi raketa. 800 voltli tizim o'ta tez zaryad olishga yordam beradi.",
        "power": 750, "top_speed": 260, "acceleration": "2.8s", "engine_type": "Dual Electric Motor",
        "fuel_consumption": "24.5 kWh/100km", "drive_type": "AWD", "cargo_capacity": "366 L",
        "rear_title": "FUTURISTIK SPORTKAR",
        "rear_description": "Minimalistik va aerodinamik shakllar uning elektr kelajak farzandi ekanligini bildiradi.",
        "interior_title": "DIGITAL COCKPIT",
        "interior_description": "To'liq digital boshqaruv, yo'lovchi uchun ham alohida ekran. Ekologik charm va sportiv o'rindiqlar.",
        "colors": [("Frozen Blue", "#a1caf1"), ("Carrara White", "#f8f8f8")],
        "amenities": ["panorama", "sport_seats", "ambient_light", "360_camera", "wireless_charging"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Mirzo Ulug'bek"],
    },
    "tesla-model-s-plaid": {
        "brand": "Tesla", "model_name": "Model S Plaid", "category": "elektro",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 5,
        "base_daily_price": 3000000, "base_deposit": 15000000, "allows_chauffeur": False,
        "short_tagline": "Yerdagi Raketa — 1020 Ot Kuchi",
        "short_description": "0-100 km/h: 2.1 sek. Eng aqlli va tezkor Tesla.",
        "detail_title": "Tesla Model S Plaid — Tezlikning Yangi Ta'rifi",
        "detail_summary": "Model S Plaid 1020 ot kuchi bilan sizni o'rindiqqa mixlab qo'yadi. Autopilot va 17 dyuymli markaziy kinoteatr-displeyi sayohatlaringizni o'zgacha qiladi.",
        "power": 1020, "top_speed": 322, "acceleration": "2.1s", "engine_type": "Tri-Motor Electric",
        "fuel_consumption": "18.5 kWh/100km", "drive_type": "AWD", "cargo_capacity": "793 L",
        "rear_title": "PLAID PERFORMANCE",
        "rear_description": "Carbon fiber spoiler va Plaid logotipi uning tezligidan nishona. Aerodinamik qarshilik o'ta past.",
        "interior_title": "MINIMALIST TECH",
        "interior_description": "Yoke rul o'zgacha boshqaruv zavqini beradi. Hech qanday ortiqcha tugma yo'q — hammasini markaziy panel orqali boshqarish mumkin.",
        "colors": [("Deep Blue Metallic", "#002366"), ("Solid Black", "#0a0a0a")],
        "amenities": ["panorama", "wireless_charging", "apple_carplay", "ambient_light", "launch_control"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Olmazor"],
    },
    "tesla-model-y": {
        "brand": "Tesla", "model_name": "Model Y", "category": "elektro",
        "fuel_type": "elektro", "transmission": "automatic", "seats": 5,
        "base_daily_price": 900000, "base_deposit": 5000000, "allows_chauffeur": False,
        "short_tagline": "Kelajak SUV'i — Minimalizm va Samaradorlik",
        "short_description": "Ko'p qirrali krossover, o'ta xavfsiz va texnologik.",
        "detail_title": "Tesla Model Y — Biznes va Oilaviy Kelajak Tanlovi",
        "detail_summary": "Model Y Tesla ning eng muvaffaqiyatli elektromobili. Keng yukxona, to'liq shisha tom va o'ta xavfsiz kuzov uni oilaviy tanlov qiladi. Avtopilot uzoq masofali sayohatlarni kamroq charchatadi.",
        "power": 384, "top_speed": 217, "acceleration": "4.8s", "engine_type": "Dual Motor Electric",
        "fuel_consumption": "16.5 kWh/100km", "drive_type": "AWD", "cargo_capacity": "854 L",
        "rear_title": "SMART KROSSOVER",
        "rear_description": "Minimalistik va silliq ko'rinish orqa qismda ham davom etadi. Shaharda va ko'p yuk bilan sayohatda ishonchli.",
        "interior_title": "OPEN SPACE",
        "interior_description": "Bitta markaziy displeydan boshqa ortiqcha detal yo'q. To'liq shisha tom yulduzlarni ko'rish imkonini beradi.",
        "colors": [("Pearl White", "#fefefe"), ("Midnight Silver", "#4c4c4c")],
        "amenities": ["panorama", "wireless_charging", "apple_carplay", "360_camera"],
        "year_range": (2023, 2024), "districts": ["Yunusobod", "Yakkasaroy"],
    },
    "toyota-camry-75": {
        "brand": "Toyota", "model_name": "Camry 75", "category": "sedan",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 5,
        "base_daily_price": 650000, "base_deposit": 3000000, "allows_chauffeur": True,
        "short_tagline": "Biznes Klas — Isbotlangan Ishonch",
        "short_description": "Yangi 75 kuzov, JBL audio va yuqori komfort.",
        "detail_title": "Toyota Camry 75 — Sifat va Ishonchning Barchaga Ma'lum Ta'rifi",
        "detail_summary": "Camry 75 O'zbekiston ko'chalarida biznes klassning ramzidir. Yumshoq podveskasi va JBL audio har bir sayohatni birinchi darajaga ko'taradi. Ishonchli motor har qanday sharoitda uzoq yashaydi.",
        "power": 203, "top_speed": 210, "acceleration": "8.2s", "engine_type": "2.5L Inline-4",
        "fuel_consumption": "7.5 L/100km", "drive_type": "FWD", "cargo_capacity": "493 L",
        "rear_title": "KOMFORTLI SEDAN",
        "rear_description": "Elegant chiziqlar va o'ziga xos orqa LED optika Camry ning klassik statusini ta'kidlaydi.",
        "interior_title": "KOMFORT VA SIFAT",
        "interior_description": "Prestige Plus pozitsiyasi bilan nappa charm va JBL audio sizga hamrohlik qiladi. Keng o'rindiqlar uzoq manzillarni yaqin qiladi.",
        "colors": [("Black", "#000"), ("White", "#fff")],
        "amenities": ["apple_carplay", "heated_seats", "wireless_charging", "360_camera"],
        "year_range": (2021, 2023), "districts": ["Yunusobod", "Mirobod", "Chilonzor"],
    },
    "toyota-land-cruiser-300": {
        "brand": "Toyota", "model_name": "Land Cruiser 300", "category": "suv",
        "fuel_type": "benzin", "transmission": "automatic", "seats": 7,
        "base_daily_price": 3500000, "base_deposit": 20000000, "allows_chauffeur": True,
        "short_tagline": "Har Yo'lning Qiroli — GR Sport",
        "short_description": "Afsonaviy LC300, yangi V6 Twin-Turbo dvigateli.",
        "detail_title": "Toyota Land Cruiser 300 — Cheksiz Quvvat va Yo'llar Qiroli",
        "detail_summary": "Yangi Land Cruiser 300 GR Sport off-road dunyosining mutlaq yetakchisi. 3.5 litrli Twin-Turbo V6 quvvat bilan birga tejamkorlikni ta'minlaydi. E-KDSS tizimi burilishlarda avtomobilning og'masligiga yordam beradi.",
        "power": 409, "top_speed": 210, "acceleration": "6.7s", "engine_type": "3.5L V6 Twin-Turbo",
        "fuel_consumption": "12.5 L/100km", "drive_type": "4WD", "cargo_capacity": "1131 L",
        "rear_title": "QIROLLIK SALOBATI",
        "rear_description": "GR Sport paketi o'ziga xosligini anglatadi. Massiv orqa dizayn va baland klirens sahro yo'llarida ishonchni saqlaydi.",
        "interior_title": "OFF-ROAD LUXURY",
        "interior_description": "GR Sport detallari bilan bezatilgan premium interyer, to'rt zonali iqlim nazorati va barcha o'rindiqlar uchun massaj tizimi.",
        "colors": [("Black Shine", "#111"), ("White Pearl", "#f5f5f0")],
        "amenities": ["panorama", "heated_seats", "360_camera", "wireless_charging", "ambient_light", "massage"],
        "year_range": (2022, 2024), "districts": ["Yunusobod", "Mirzo Ulug'bek"],
    },
}
