# Generated by Django 6.0.3 on 2026-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_notification_options_notification_admin_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Mijoz'), ('operator', 'Operator'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
