# Generated by Django 6.0.4 on 2026-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0003_alter_district_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
