# Generated by Django 5.2.1 on 2026-04-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='UZS', max_length=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('terminal', 'Terminal'), ('transfer', 'Bank Transfer')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock Gateway'), ('stripe', 'Stripe'), ('payme', 'Payme'), ('click', 'Click')], default='mock', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'INITIATED'), ('otp_pending', 'OTP_PENDING'), ('authorized', 'AUTHORIZED'), ('paid', 'PAID'), ('failed', 'FAILED'), ('refunded', 'REFUNDED')], default='initiated', max_length=20),
        ),
    ]
