# Generated by Django 6.0.3 on 2026-04-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_paymenttransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinginvoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deposithold',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('terminal', 'Terminal'), ('transfer', 'Bank Transfer')], db_index=True, default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock Gateway'), ('stripe', 'Stripe'), ('payme', 'Payme'), ('click', 'Click')], db_index=True, default='mock', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'INITIATED'), ('otp_pending', 'OTP_PENDING'), ('authorized', 'AUTHORIZED'), ('paid', 'PAID'), ('failed', 'FAILED'), ('refunded', 'REFUNDED')], db_index=True, default='initiated', max_length=20),
        ),
    ]
