# Generated by Django 5.2.1 on 2026-04-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_chauffeur_details_booking_is_chauffeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('coverage_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite')], max_length=20)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('covers_collision', models.BooleanField(default=False)),
                ('covers_theft', models.BooleanField(default=False)),
                ('covers_natural_disaster', models.BooleanField(default=False)),
                ('covers_roadside_assistance', models.BooleanField(default=False)),
                ('covers_personal_accident', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BookingInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('policy_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='bookings.booking')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.insuranceplan')),
            ],
        ),
    ]
